# Generated by Django 4.1.4 on 2022-12-13 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('numer_seryjny', models.CharField(max_length=50)),
                ('numer_inwentarzowy', models.CharField(max_length=6)),
                ('osoba', models.CharField(max_length=50)),
                ('data_utworzenia', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
