# Generated by Django 4.1.4 on 2022-12-13 17:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='Sprzet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('numer_seryjny', models.CharField(max_length=50)),
                ('numer_inwentarzowy', models.CharField(max_length=6)),
                ('osoba', models.CharField(max_length=50)),
                ('data_utworzenia', models.DateTimeField(default=django.utils.timezone.now)),
                ('kategoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.kategoria')),
            ],
            options={
                'verbose_name': 'Sprzet',
                'verbose_name_plural': 'Sprzety',
            },
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
    ]
