# Generated by Django 4.1.4 on 2022-12-13 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_producent_sprzet_producent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lokalizacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Lokalizacja',
                'verbose_name_plural': 'Lokalizacje',
            },
        ),
        migrations.AlterField(
            model_name='sprzet',
            name='nazwa',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sprzet',
            name='numer_inwentarzowy',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='sprzet',
            name='numer_seryjny',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sprzet',
            name='osoba',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sprzet',
            name='lokalizacja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.lokalizacja'),
        ),
    ]
