# Generated by Django 4.1.4 on 2022-12-13 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_lokalizacja_alter_sprzet_nazwa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprzet',
            name='osoba',
        ),
    ]
