# Generated by Django 4.1.4 on 2022-12-16 09:34

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_alter_sprzet_data_utworzenia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprzet',
            name='data_utworzenia',
            field=models.DateTimeField(default=django.utils.datetime_safe.date.today),
        ),
    ]
