# Generated by Django 4.1.4 on 2022-12-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_alter_sprzet_data_utworzenia'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprzet',
            name='zdjecie',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
