# Generated by Django 4.1.4 on 2022-12-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0012_alter_sprzet_data_utworzenia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprzet',
            name='data_utworzenia',
            field=models.DateTimeField(),
        ),
    ]
