# Generated by Django 4.1.4 on 2023-01-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0018_sprzet_qr_code_alter_sprzet_data_utworzenia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprzet',
            name='QR_code',
            field=models.ImageField(blank=True, upload_to='QR_code/'),
        ),
    ]
